apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-delete-task
spec:
  replicas: {{ .Values.deleteTask.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-delete-task
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-delete-task
    spec:
      containers:
      - name: {{ .Release.Name }}-delete-task
        image: {{ .Values.common.acrURL }}/{{ .Values.deleteTask.image.name }}/{{ .Values.deleteTask.image.tag }}
        ports:
        - containerPort: {{ .Values.deleteTask.port }}
        env:
        - name: CONNECTION_STRING
          value: {{ .Values.common.connectionString }}