apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-delete-task
spec:
  selector:
    {{ .Release.Name }}-delete-task
  ports:
    - port: {{ .Values.delete-task.servicePort }}
      targetPort: {{ .Values.delete-task.port }}
  type: ClusterIP