apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-get-task
spec:
  replicas: {{ .Values.getTask.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-get-task
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-get-task
    spec:
      containers:
      - name: {{ .Release.Name }}-get-task
        image: {{ .Values.common.acrURL }}/{{ .Values.getTask.image.name }}:{{ .Values.getTask.image.tag }}
        ports:
        - containerPort: {{ .Values.getTask.port }}
        env:
        - name: CONNECTION_STRING
          value: {{ .Values.common.connectionString }}