apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-get-task
  annotations:
    kubernetes.io/ingress.class: {{ .Values.common.ingressClassName }}
spec:
  rules:
  - host: {{ .Values.getTask.ingress.host }}
    http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
                service:
                    name: {{ .Release.Name }}-get-task
                    port:
                      number: {{ .Values.getTask.servicePort }}