apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-get-task
spec:
  selector:
    app: {{ .Release.Name }}-get-task
  ports:
    - port: {{ .Values.getTask.servicePort }}
      targetPort: {{ .Values.getTask.port }}
  type: ClusterIP