apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-get-task
spec:
  selector:
    {{ .Release.Name }}-get-task
  ports:
    - port: {{ .Values.get-task.servicePort }}
      targetPort: {{ .Values.get-task.port }}
  type: ClusterIP