apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-add-task
spec:
  selector:
    app: {{ .Release.Name }}-add-task
  ports:
    - port: {{ .Values.addTask.servicePort }}
      targetPort: {{ .Values.addTask.port }}
  type: ClusterIP