apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-add-task
spec:
  selector:
    app: {{ .Release.Name }}-add-task
  ports:
    - port: {{ .Values.add-task.servicePort }}
      targetPort: {{ .Values.add-task.port }}
  type: ClusterIP