apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ui
spec:
  selector:
    app: {{ .Release.Name }}-ui
  ports:
    - port: {{ .Values.ui.servicePort }}
      targetPort: {{ .Values.ui.port }}
  type: ClusterIP

  